### ISSUE TITLE
Incorrect handling of results from the field checkbox

### ISSUE THREAD

**Issue by IN80** [mnoskov/formresults#3]
Hello.

Data with results from the checkbox is not displayed.
When you select several results: the data is in the form: 1; 2; 3

Data is transferred to mysql in the form: `"name": ["1", "2", "3"]`. When corrected to `"name":"1, 2, 3"`, it worked.

**Comment by mnoskov** [comment]
https://github.com/mnoskov/formresults/commit/687d94b22fba5d6cc1e77e4c8253b2f21e0336af
